#!/bin/bash
update_packages() {
  echo "Updating APT package listings"
  sudo apt update
}

install_docker() {
  echo "Install Docker engine"
  sudo apt install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release -y
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  sudo apt-get install docker-ce docker-ce-cli containerd.io -y
  sudo usermod -aG docker ubuntu
}

install_unzip() {
  echo "Install unzip"
  sudo apt install unzip
}

install_aws_cli() {
  echo "Install aws cli"
  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
  unzip awscliv2.zip
  sudo ./aws/install
}

install_java() {
  echo "Install Java"
  sudo apt install fontconfig openjdk-17-jre -y
}

install_jenkins() {
  echo "Install Jenkins"
  sudo wget -O /usr/share/keyrings/jenkins-keyring.asc https://pkg.jenkins.io/debian/jenkins.io-2023.key
  echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
  sudo apt-get install jenkins -y
  echo "Setup docker In Jenkins"
  sudo usermod -a -G docker jenkins
  echo "Changing the permissions on the Docker socket to allow the 'docker' group to read and write..."
  sudo chmod 666 /var/run/docker.sock
  echo "Start and Enable Jenkins"
  sudo systemctl start jenkins
  sudo systemctl enable jenkins
}

install_kubectl() {
  echo "Install kubectl"
  curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
  curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
  echo "$(<kubectl.sha256) kubectl" | sha256sum --check
  chmod +x kubectl
  sudo mv ./kubectl /usr/local/bin/kubectl
  kubectl version --client
}

update_packages
install_docker
install_unzip
install_aws_cli
install_java
install_jenkins
install_kubectl